services:
  postgres_db:
    container_name: postgres_db
    image: postgres:17.2-alpine3.21
    restart: always
    networks:
      - app-network
    env_file:
      - .env.production
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.4.2-alpine
    restart: always
    networks:
      - app-network
    env_file:
      - .env.production
    volumes:
      - redis_data:/data
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"

  nestjs:
    depends_on:
      - redis
      - postgres_db
    restart: always
    container_name: nestjs
    build: ./backend
    networks:
      - app-network
    volumes:
      - nestjs:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    env_file:
      - .env.production
    command: npm run start:prod

  nuxt:
    build: ./frontend
    container_name: nuxt
    restart: always
    volumes:
      - nuxt:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.production.front
    networks:
      - app-network
    command: npm run start:prod

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./backend/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/deploy/nginx/sportikapp.ru.crt:/etc/nginx/ssl/sportikapp.ru.crt
      - ./backend/deploy/nginx/sportikapp.ru.key:/etc/nginx/ssl/sportikapp.ru.key
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443

  # certbot:
  #   container_name: certbot
  #   restart: always
  #   ports:
  #     - '6000:80'
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./backend/deploy/nginx/:/etc/nginx/
  #   build:
  #     context: ./backend/deploy/ssl/certbot
  #     dockerfile: Dockerfile
  #     args:
  #       DOMAIN_EMAIL: dendiroblek@gmail.com
  #       DOMAIN_URL: your_domain.com

volumes:
  redis_data:
  postgres_db:
  nestjs:
  nuxt:

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
